apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: pod
  volumes:
    - name: pod
      persistentVolumeClaim:
        claimName: podpvc