apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: qq2
spec:
  containers:
    - image: nginx
      name: pod
      volumeMounts:
        - name: www
          mountPath: /data
  volumes:
    - name: www
      persistentVolumeClaim:
        claimName: podpvc
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: data
