apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: staging
data:
  APP_ENV: "staging"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: staging
data:
  DB_USER: YWRtaW4K
  DB_PASSWORD: cGFzc3dvcmQxMjMK
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: staging
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: app_env
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: log_level
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD