apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-stateful
spec:
  selector:
    matchLabels:
      app: web-stateful
  serviceName: "web-stateful"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: web-stateful
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: pvc-data
      containers:
      - name: nginx
        image: nginx:stable
        volumeMounts:
        - name: pvc-data
          mountPath: /usr/share/nginx/html