apiVersion: v1
kind: Pod
metadata:
  name: limit
  namespace: qq3
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"